name: jp_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  blurrycontainer: ^0.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bg_startscreen.png
    - assets/chick cupcakes_3D.png
    - assets/T2.png
    - assets/bg_mainscreen.png
    - assets/Burger_3D.png
    - assets/Ice.cream.png
    - assets/ice cream stick_3D.png
    - assets/cat cupcakes_3D.png
    - assets/Icecream_3D.png
